CREATE TABLE `ga_compiled_daily_log` (
  `log_srl` bigint(11) NOT NULL AUTO_INCREMENT,
  `ua` char(1) NOT NULL,
  `source` varchar(50) NOT NULL,
  `rst_type` varchar(5) NOT NULL DEFAULT '0',
  `media` varchar(10) NOT NULL,
  `brd` TINYINT NOT NULL DEFAULT '0',
  `campaign_1st` varchar(100) NOT NULL DEFAULT '0',
  `campaign_2nd` varchar(25) NOT NULL DEFAULT '0',
  `campaign_3rd` varchar(25) NOT NULL DEFAULT '0',
  `term` varchar(1000) NOT NULL DEFAULT '0',
  `session` MEDIUMINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `new_per`  varchar(20) NOT NULL DEFAULT '0',
  `bounce_per` varchar(20) NOT NULL DEFAULT '0',
  `duration_sec` varchar(20) NOT NULL DEFAULT '0',
  `pvs` varchar(20) NOT NULL DEFAULT '0',
  `transactions` SMALLINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `revenue` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `registrations` SMALLINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `logdate` DATE NOT NULL,
  `regdate` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`log_srl`),
  KEY `idx_dt` (`logdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;