"""
Django settings for svdjango project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import socket  # allow server ip automatically
from pathlib import Path
import os.path  # do not import os
import configparser  # https://docs.python.org/3/library/configparser.html

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# allow server IP
ALLOWED_HOSTS = ['127.0.0.1', socket.gethostbyname(socket.getfqdn())]

# allow designated server domain name
# s_domain_name_txt = os.path.join(BASE_DIR, 'domain_names.txt')
s_domain_name_txt = os.path.join(BASE_DIR, 'conf', 'allowed_domain_names.txt')
if os.path.isfile(s_domain_name_txt):
    with open(s_domain_name_txt) as f:
        s_domain_names = f.read().strip()
    lst_domain_name = s_domain_names.splitlines()
    for s_domain_name in lst_domain_name:
        ALLOWED_HOSTS.append(s_domain_name)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open(os.path.join(BASE_DIR, 'conf', 'django_secret_key.txt')) as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'channels',  # web socket - # pip install -U channels
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'svextract.apps.SvextractConfig',
    'svauth',  # for user model customization
]

AUTH_USER_MODEL = 'svauth.User'

# Channels
ASGI_APPLICATION = 'svdjango.routing.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'svdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'svdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
o_mysql_config = configparser.RawConfigParser()  # make python3 config parser parse key case sensitive
o_mysql_config.optionxform = lambda option: option  # make python3 config parser parse key case sensitive
s_mysql_config_file = os.path.join(BASE_DIR, 'conf', 'mysql_config.ini')
with open(s_mysql_config_file) as f:
    o_mysql_config.read_file(f)
o_mysql_config.read(s_mysql_config_file)

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 3600,  # https://stackoverflow.com/questions/26958592/django-after-upgrade-mysql-server-has-gone-away
        'NAME': o_mysql_config['SERVER']['db_database'],  # 'sv_test',
        'USER': o_mysql_config['SERVER']['db_userid'],  # 'w9721066',
        'PASSWORD': o_mysql_config['SERVER']['db_password'],  # 'w58648245!',
        'HOST': o_mysql_config['SERVER']['db_hostname'],  # '127.0.0.1',
        'PORT': o_mysql_config['SERVER']['db_port'],  # '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
