CREATE TABLE `compiled_ga_media_daily_log` (
  `log_srl` bigint(11) NOT NULL AUTO_INCREMENT,
  `media_agency_id` BIGINT(11) DEFAULT 0,
  `media_ua` char(1) NOT NULL,
  `media_term` varchar(1000) NOT NULL,
  `media_source` varchar(50) NOT NULL,
  `media_rst_type` varchar(5) NOT NULL,
  `media_media` varchar(10) NOT NULL,
  `media_brd` TINYINT NOT NULL DEFAULT 0,
  `media_camp1st` varchar(100) NOT NULL,
  `media_camp2nd` varchar(25) DEFAULT NULL,
  `media_camp3rd` varchar(25) DEFAULT NULL,
  `media_raw_cost` bigint(11) DEFAULT 0,
  `media_agency_cost` bigint(11) DEFAULT 0,
  `media_cost_vat` bigint(11) DEFAULT 0,
  `media_imp` bigint(11) DEFAULT 0,
  `media_click` MEDIUMINT(11) DEFAULT 0,
  `media_conv_cnt` MEDIUMINT(11) DEFAULT 0,
  `media_conv_amnt` bigint(11) DEFAULT 0,
  `in_site_tot_session` MEDIUMINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `in_site_tot_new`  MEDIUMINT(11) NOT NULL DEFAULT '0',
  `in_site_tot_bounce` MEDIUMINT(11) NOT NULL DEFAULT '0',
  `in_site_tot_duration_sec` MEDIUMINT(11) NOT NULL DEFAULT '0',
  `in_site_tot_pvs` MEDIUMINT(11) NOT NULL DEFAULT '0',
  `in_site_trs` SMALLINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `in_site_revenue` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `in_site_registrations` SMALLINT(11) UNSIGNED NOT NULL DEFAULT 0,
  `logdate` DATE NOT NULL,
  `regdate` DATETIME DEFAULT NOW(),
   PRIMARY KEY (`log_srl`),
   KEY `idx_logdate` (`logdate`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;