# Generated by Django 3.2.5 on 2022-02-25 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_acct_title', models.CharField(max_length=100, unique=True, verbose_name='구좌 명칭')),
                ('b_approval', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_brand_title', models.CharField(max_length=100, verbose_name='브랜드 명칭')),
                ('b_approval', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('sv_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svacct.account', verbose_name='구좌 명칭')),
            ],
            options={
                'unique_together': {('sv_acct', 's_brand_title')},
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_data_source', models.IntegerField(choices=[(0, '선택하세요'), (1, '구글 애널리틱스'), (2, '구글 광고'), (3, '페이스북 광고'), (4, '네이버 광고'), (5, '카카오 모멘트')], default=0, verbose_name='데이터 소스')),
                ('b_approval', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('sv_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svacct.brand', verbose_name='브랜드 명칭')),
            ],
            options={
                'unique_together': {('sv_brand', 'n_data_source')},
            },
        ),
        migrations.CreateModel(
            name='DataSourceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_data_source_serial', models.CharField(max_length=50, verbose_name='데이터 소스 일련번호')),
                ('b_approval', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('sv_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svacct.datasource', verbose_name='데이터 소스')),
            ],
            options={
                'unique_together': {('sv_data_source', 's_data_source_serial')},
            },
        ),
    ]
