# Generated by Django 3.2.5 on 2022-01-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svacct', '0001_initial'),
        ('svauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_owners',
            field=models.ManyToManyField(to='svacct.Brand'),
        ),
    ]
